### ISSUE TITLE
Error inflating class android.widget.ImageView in FeedbackActivity

### ISSUE THREAD

**Issue by asaf-demetria** [bugfender/rn-bugfender#24]
### Device details
Google Pixel 3XL
Android 9.0
rn-bugfender version 1.14

### Description
We've encountered some weird crash, which may not be related directly to Bugfnder.
It happens on app startup. Here's the stack trace:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{my.app/com.bugfender.sdk.ui.FeedbackActivity}: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class android.widget.ImageView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Have you seen it before? Would you need any other details?

**Comment by jgimenez** [comment]
Hi there, following up on our previous conversation, this is an error that only happens during automated tests and, according to our records, never affects real users. We just published an update of the Android SDK (version 3.0.10) that removes this exception during automated testing. Thanks for reporting it!
