### ISSUE TITLE
Error installing pods in a M1 Mac

### ISSUE THREAD

**Issue by edu-zamora** [bugfender/rn-bugfender#49]
### Command

```
/Users/edu/.asdf/installs/ruby/3.1.2/bin/pod install
```

### Report

* What did you do?

- Install Bugfender: `yarn add @bugfender/rn-bugfender`
- Try to install pods: `cd ios && pod install`

* What did you expect to happen?

I expected the pods to be installed successfully.

* What happened instead?

Installing pods failed with the next error (for the full stacktrace, you can check the Error section below):
```
LoadError - dlopen(/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried: '/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')) - /Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi_c.bundle
```

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
    RubyGems : 3.3.7
        Host : macOS 12.3 (21E230)
       Xcode : 13.1 (13A1030d)
         Git : git version 2.37.1
Ruby lib dir : /Users/edu/.asdf/installs/ruby/3.1.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

inhibit_all_warnings!

target 'DemoApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  target 'DemoAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] =  "arm64"
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
      end
    end
    flipper_post_install(installer)
  end
end

target 'DemoApp-tvOS' do
  # Pods for DemoApp-tvOS

  target 'DemoApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

### Error

```
LoadError - dlopen(/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried: '/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')) - /Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi_c.bundle
<internal:/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `rescue in <top (required)>'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi.rb:2:in `<top (required)>'
<internal:/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/ethon-0.15.0/lib/ethon.rb:3:in `<top (required)>'
<internal:/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
<internal:/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:284:in `ensure_versions_file_loaded'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:208:in `search'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `each'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by!'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Users/edu/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/Users/edu/.asdf/installs/ruby/3.1.2/bin/pod:25:in `load'
/Users/edu/.asdf/installs/ruby/3.1.2/bin/pod:25:in `<main>'
```

**Comment by jgimenez** [comment]
hi Edu, is this related to Bugfender in any way? I don't see it mentioned in any of the error messages

**Comment by edu-zamora** [comment]
@jgimenez Yes, it is. Installing pods works successfully before adding `@bugfender/rn-bugfender`, fails after adding it and works again if I remove `@bugfender/rn-bugfender`.

This happens consistently, so everything points out to this being an issue with `@bugfender/rn-bugfender`.

**Comment by jgimenez** [comment]
OK, I'll see if we can reproduce in any way. If you have any further details mentioning which file or which specific error happened, please let us know.

**Comment by edu-zamora** [comment]
That's the whole stacktrace, so that's unfortunately all the info we have.

Given the `'x86_64', need 'arm64e'` part, my guess is that `@bugfender/rn-bugfender` might not support all possible architectures.

**Comment by vilanovi** [comment]
Hello @edu-zamora, quickly asking here regarding M1 macs and Cocoapods:

If you have Cocoapods installed via gem, it doesn't support the AppleSilicon chips properly. Instead, each time you have to install a new pod, you have to use rosetta: `arch -x86_64 pod install`. 

The issue you point above seems to be related to `ffi`, which is the actual dependency of Cocoapods that is not supported in Apple Silicon. 

Therefore, have you Cocoapods installed via gem? Are you running pod install with rosetta (`arch -x86_64`)? could you try and see if these errors repeat?

Thanks,

**Comment by edu-zamora** [comment]
@vilanovi I had already tried using `arch -x86_64 pod install` and it still didn't work, but reinstalling Cocoapods with brew made it finally work:

```sh
sudo gem uninstall cocoapods
brew install cocoapods
pod install
```

Thank you a lot for looking into this! 😄
